import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Attendance, CoachingClass, Fee, FeePayment, Marks, Student } from '../types';

const addHeader = (doc: jsPDF, title: string, coachingClass?: CoachingClass | null) => {
  doc.setFillColor(37, 99, 235);
  doc.roundedRect(14, 12, 182, 28, 4, 4, 'F');

  doc.setFillColor(255, 255, 255);
  doc.circle(28, 26, 8, 'F');
  doc.setTextColor(37, 99, 235);
  doc.setFontSize(14);
  doc.text('TF', 23.7, 29.2);

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text(title, 42, 24);
  doc.setFontSize(11);
  doc.text(coachingClass?.name ?? 'TeachFlow Coaching Class', 42, 31);
};

const addMeta = (doc: jsPDF) => {
  doc.setTextColor(75, 85, 99);
  doc.setFontSize(10);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 48);
};

const addStudentCard = (doc: jsPDF, student: Student) => {
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 54, 182, 24, 3, 3);
  doc.setTextColor(17, 24, 39);
  doc.setFontSize(12);
  doc.text(`Student: ${student.name}`, 20, 64);
  doc.text(`Batch: ${student.batch}`, 100, 64);
  doc.text(`Roll Number: ${student.rollNumber}`, 20, 72);
  doc.text(`Email: ${student.email}`, 100, 72);
};

const addFooter = (doc: jsPDF) => {
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(10);
  doc.setTextColor(107, 114, 128);
  doc.text('Generated by TeachFlow', 14, pageHeight - 10);
};

const saveDocument = (doc: jsPDF, filename: string) => {
  addFooter(doc);
  doc.save(filename);
};

export const pdfService = {
  downloadFeeReceipt(fee: Fee, payment: FeePayment, student?: Student, coachingClass?: CoachingClass | null) {
    const doc = new jsPDF();
    addHeader(doc, 'TeachFlow Fee Receipt', coachingClass);
    addMeta(doc);

    if (student) {
      addStudentCard(doc, student);
    }

    autoTable(doc, {
      startY: student ? 86 : 58,
      head: [['Receipt No', 'Payment Date', 'Method', 'Amount']],
      body: [[payment.receiptNumber, payment.paidDate, payment.method, `INR ${payment.amount}`]],
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
    });

    autoTable(doc, {
      startY: (doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY
        ? ((doc as jsPDF & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY ?? 90) + 10
        : 110,
      head: [['Fee Item', 'Value']],
      body: [
        ['Description', fee.description],
        ['Total Fee', `INR ${fee.amount}`],
        ['Paid So Far', `INR ${fee.paidAmount}`],
        ['Status', fee.status],
        ['Generated By', 'TeachFlow'],
      ],
      theme: 'striped',
      headStyles: { fillColor: [15, 118, 110] },
    });

    saveDocument(doc, `${payment.receiptNumber}.pdf`);
  },

  downloadStudentReport(student: Student, marks: Marks[], coachingClass?: CoachingClass | null) {
    const doc = new jsPDF();
    addHeader(doc, 'TeachFlow Marks Report', coachingClass);
    addMeta(doc);
    addStudentCard(doc, student);

    autoTable(doc, {
      startY: 86,
      head: [['Exam', 'Subject', 'Type', 'Date', 'Score', 'Percentage']],
      body: marks.map((mark) => [
        mark.examName,
        mark.subject,
        mark.examType,
        mark.date,
        `${mark.obtainedMarks}/${mark.totalMarks}`,
        `${Math.round((mark.obtainedMarks / mark.totalMarks) * 100)}%`,
      ]),
      theme: 'grid',
      headStyles: { fillColor: [37, 99, 235] },
    });

    saveDocument(doc, `${student.rollNumber}-marks-report.pdf`);
  },

  downloadAttendanceReport(student: Student, attendance: Attendance[], coachingClass?: CoachingClass | null) {
    const doc = new jsPDF();
    addHeader(doc, 'TeachFlow Attendance Report', coachingClass);
    addMeta(doc);
    addStudentCard(doc, student);

    autoTable(doc, {
      startY: 86,
      head: [['Lecture', 'Batch', 'Date', 'Status']],
      body: attendance.map((item) => [
        item.lectureTitle ?? 'Lecture',
        item.batch ?? student.batch,
        (item.date ?? item.markedAt).slice(0, 10),
        item.status,
      ]),
      theme: 'striped',
      headStyles: { fillColor: [22, 163, 74] },
    });

    saveDocument(doc, `${student.rollNumber}-attendance-report.pdf`);
  },

  downloadFeeSummary(student: Student, fees: Fee[], coachingClass?: CoachingClass | null) {
    const doc = new jsPDF();
    addHeader(doc, 'TeachFlow Fee Summary', coachingClass);
    addMeta(doc);
    addStudentCard(doc, student);

    autoTable(doc, {
      startY: 86,
      head: [['Description', 'Due Date', 'Status', 'Amount', 'Paid']],
      body: fees.map((fee) => [
        fee.description,
        fee.dueDate,
        fee.status,
        `INR ${fee.amount}`,
        `INR ${fee.paidAmount}`,
      ]),
      theme: 'grid',
      headStyles: { fillColor: [234, 88, 12] },
    });

    saveDocument(doc, `${student.rollNumber}-fee-summary.pdf`);
  },
};
