import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import { CoachingClass, Fee, FeePayment, Student } from '../types/Models';

const escapeHtml = (value: string) =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const currency = (amount: number) => `INR ${Math.max(0, amount).toLocaleString('en-IN')}`;

const wrapHtml = (title: string, body: string) => `
  <html>
    <head>
      <meta charset="utf-8" />
      <style>
        body { font-family: Helvetica, Arial, sans-serif; padding: 24px; color: #111827; }
        .header { background: #1d4ed8; color: white; padding: 18px 20px; border-radius: 16px; }
        .header h1 { margin: 0 0 6px; font-size: 24px; }
        .header p { margin: 0; font-size: 12px; opacity: 0.9; }
        .card { border: 1px solid #d1d5db; border-radius: 14px; padding: 16px; margin-top: 18px; }
        .row { display: flex; justify-content: space-between; gap: 12px; margin: 8px 0; }
        .label { color: #6b7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.08em; }
        .value { font-size: 14px; font-weight: 600; }
        .footer { margin-top: 24px; color: #6b7280; font-size: 12px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>${escapeHtml(title)}</h1>
        <p>Generated on ${escapeHtml(new Date().toLocaleString('en-IN'))}</p>
      </div>
      ${body}
      <div class="footer">Generated by TeachFlow</div>
    </body>
  </html>
`;

const sharePdf = async (html: string, filename: string) => {
  const { uri } = await Print.printToFileAsync({ html });
  if (await Sharing.isAvailableAsync()) {
    await Sharing.shareAsync(uri, { mimeType: 'application/pdf', dialogTitle: filename, UTI: '.pdf' });
  }
  return uri;
};

export const pdfService = {
  async shareFeeReceipt(fee: Fee, payment: FeePayment, student?: Student | null, coachingClass?: CoachingClass | null) {
    const html = wrapHtml(
      'TeachFlow Fee Receipt',
      `
        <div class="card">
          <div class="row"><div><div class="label">Class</div><div class="value">${escapeHtml(coachingClass?.name ?? 'TeachFlow Class')}</div></div><div><div class="label">Receipt</div><div class="value">${escapeHtml(payment.receiptNumber)}</div></div></div>
          <div class="row"><div><div class="label">Student</div><div class="value">${escapeHtml(student?.name ?? fee.studentName)}</div></div><div><div class="label">Roll</div><div class="value">${escapeHtml(student?.rollNumber ?? '-')}</div></div></div>
          <div class="row"><div><div class="label">Method</div><div class="value">${escapeHtml(payment.method.toUpperCase())}</div></div><div><div class="label">Date</div><div class="value">${escapeHtml(payment.paidDate)}</div></div></div>
        </div>
        <div class="card">
          <div class="row"><div><div class="label">Fee Item</div><div class="value">${escapeHtml(fee.description)}</div></div><div><div class="label">Total</div><div class="value">${escapeHtml(currency(fee.amount))}</div></div></div>
          <div class="row"><div><div class="label">Paid This Time</div><div class="value">${escapeHtml(currency(payment.amount))}</div></div><div><div class="label">Paid So Far</div><div class="value">${escapeHtml(currency(fee.paidAmount))}</div></div></div>
          <div class="row"><div><div class="label">Status</div><div class="value">${escapeHtml(fee.status.toUpperCase())}</div></div><div><div class="label">Due Date</div><div class="value">${escapeHtml(fee.dueDate)}</div></div></div>
        </div>
      `
    );

    return sharePdf(html, `${payment.receiptNumber}.pdf`);
  },

  async shareInvoice(input: {
    title?: string;
    fee: Fee;
    student?: Student | null;
    coachingClass?: CoachingClass | null;
    payment?: FeePayment | null;
    invoiceNumber: string;
  }) {
    const html = wrapHtml(
      input.title ?? 'TeachFlow Invoice',
      `
        <div class="card">
          <div class="row"><div><div class="label">Invoice No</div><div class="value">${escapeHtml(input.invoiceNumber)}</div></div><div><div class="label">Class</div><div class="value">${escapeHtml(input.coachingClass?.name ?? 'TeachFlow Class')}</div></div></div>
          <div class="row"><div><div class="label">Student</div><div class="value">${escapeHtml(input.student?.name ?? input.fee.studentName)}</div></div><div><div class="label">Date</div><div class="value">${escapeHtml((input.payment?.paidDate ?? input.fee.paymentDate ?? input.fee.paidDate ?? input.fee.dueDate).slice(0, 10))}</div></div></div>
        </div>
        <div class="card">
          <div class="row"><div><div class="label">Amount</div><div class="value">${escapeHtml(currency(input.payment?.amount ?? input.fee.amount))}</div></div><div><div class="label">Status</div><div class="value">${escapeHtml(input.fee.status.toUpperCase())}</div></div></div>
          <div class="row"><div><div class="label">Fee Item</div><div class="value">${escapeHtml(input.fee.description)}</div></div><div><div class="label">Payment Method</div><div class="value">${escapeHtml((input.payment?.method ?? input.fee.paymentMethod ?? 'manual').toUpperCase())}</div></div></div>
        </div>
      `
    );

    return sharePdf(html, `${input.invoiceNumber}.pdf`);
  },
};
